language: c++
sudo: false
before_install:
  - sh -c 'cd code && source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)'
script:
  - sh -c 'cd code && build_platform uno'
notifications:
email:
  on_success: change
  on_failure: change
