sudo: false
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq arduino
script:
  - sh -c 'cd code && ./build.sh'
notifications:
  email:
    on_success: change
    on_failure: change
