sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq arduino
script:
  - cd code
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_1.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :1 -ac -screen 0 1280x1024x16
  - sleep 3
  - export DISPLAY=:1.0
  - sh build.sh
notifications:
  email:
    on_success: change
    on_failure: change
