sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq arduino
script:
  - cd code
  - ./build-headless.sh
notifications:
  email:
    on_success: change
    on_failure: change
